# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Halbert Chen
email: hobo0cn@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Halbert Chen's</h3><h1>Resume</h1><h3>I am a Programer!</h3>Hope you know it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hobo0cn.github.io" # the base hostname & protocol for your site
twitter_username: hobo0cn
github_username:  hobo0cn

# Build settings
markdown: kramdown
